del mgr\*.obj
del mgr\*.exe
del mgr\trfile
del ttest\*.obj
del ttest\*.exe
del ttest\*.res
del ttest\trfile
del mtest\*.obj
del mtest\*.exe
del mtest\*.res
del mtest\*.h
del mtest\trfile
del doc\res*
del doc\*.obj
del doc\*.exe
del doc\*.h
del doc\trfile
del envir\trfile
del out\trfile
del lib\*.new
del lib\*.old
del lib\*.cpp
